### ISSUE TITLE
Installing the app causes errors

### ISSUE THREAD

**Issue by webiummedia** [elastic/app-search-reference-ui-react#49]

**Comment by webiummedia** [comment]
Hey guys I am trying to install the app on my centos server and this is what i get when i try the install command

```
[root@mail widget]# npm install
npm WARN lifecycle app-search-reference-ui-react@1.2.0~postinstall: cannot run in wd %s %s (wd=%s) app-search-reference-ui-react@1.2.0 npm-run-all build-css /home/frontend/public_html/wp-content/plugins/PatSearch/widget
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none was installed.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none was installed.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/eslint-plugin@2.x but none was installed.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/parser@2.x but none was installed.
```

**Comment by webiummedia** [comment]
When i try npm start I get

```
[root@mail widget]# npm start

> app-search-reference-ui-react@1.2.0 start /home/frontend/public_html/wp-content/plugins/PatSearch/widget
> react-scripts start

/home/frontend/public_html/wp-content/plugins/PatSearch/widget/node_modules/react-dev-utils/WebpackDevServerUtils.js:167
  compiler.hooks.done.tap('done', async stats => {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/frontend/public_html/wp-content/plugins/PatSearch/widget/node_modules/react-scripts/scripts/start.js:45:5)

npm ERR! Linux 3.10.0-957.27.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! app-search-reference-ui-react@1.2.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-search-reference-ui-react@1.2.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app-search-reference-ui-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app-search-reference-ui-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app-search-reference-ui-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/frontend/public_html/wp-content/plugins/PatSearch/widget/npm-debug.log
```

**Comment by JasonStoltz** [comment]
@webiummedia  Hi Pat,

Can you try running some of the npm commands from `package.json` directly and see which one is failing?

For example:
```
npm run build-css
npm run build-js
```

Also try:
```
rm package-lock.json
rm -rf node_modules/
npm install
```

**Comment by JasonStoltz** [comment]
Also,

could you please provide the out of the following?
```
node -v
```
```
npm -v
```

**Comment by JasonStoltz** [comment]
I don't know much about centos, but it would appear that it is an unsupported OS for some of our build dependencies:

```
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by webiummedia** [comment]
I found out that yum install did not install the last version of nodejs. Using nvm and manualy choosing the last build did the trick.
